name: Deploy Telethon

on: 
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟触发一次
  push: 
    branches: 
      - master  # 当推送到 master 分支时触发
  workflow_dispatch:  # 支持手动触发

jobs:
  run-telethon-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decrypt Telethon session file
      env:
        API_ID: ${{ secrets.API_ID }}
        SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}
      run: |
        openssl aes-256-cbc -d -pbkdf2 -in "${{ secrets.API_ID }}session_name.session.enc" -out "${{ secrets.API_ID }}session_name.session" -pass pass:"${{ secrets.SESSION_PASSWORD }}"

    - name: Get previous workflow run ID
      uses: actions/github-script@v6
      id: get-previous-run-id
      with:
        script: |
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml',  // 使用 main.yml 作为 workflow_id
            per_page: 1,
            status: 'success',
          });
          if (runs.data.workflow_runs.length > 0) {
            core.setOutput('run_id', runs.data.workflow_runs[0].id);
          } else {
            core.setFailed('No previous successful workflow run found');
          }
      continue-on-error: true

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: last_read_message
        path: .
        run-id: ${{ steps.get-previous-run-id.outputs.run_id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Run Telethon script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        WORK_BOT_ID: ${{ secrets.WORK_BOT_ID }}
        WORK_CHAT_ID: ${{ secrets.WORK_CHAT_ID }}
        PUBLIC_BOT_ID: ${{ secrets.PUBLIC_BOT_ID }}
        WAREHOUSE_CHAT_ID: ${{ secrets.WAREHOUSE_CHAT_ID }}
        LINK_CHAT_ID: ${{ secrets.LINK_CHAT_ID }}
      run: |
        python go.py

    - name: Check if last_read_message_id.json was created
      run: |
        if [ -f last_read_message_id.json ]; then
          echo "last_read_message_id.json was created."
        else
          echo "last_read_message_id.json was not created."
        fi

    - name: Upload last_read_message_id.json artifact
      uses: actions/upload-artifact@v4
      with:
        name: last_read_message
        path: last_read_message_id.json

    - name: Delete old workflow runs
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # 使用个人访问令牌
        script: |
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml',  // 使用 main.yml 作为 workflow_id
            per_page: 100,  // 获取最多100个运行
          });

          console.log('Found workflow runs:', runs.data.workflow_runs.length);

          const runIdsToDelete = runs.data.workflow_runs.slice(4).map(run => run.id);

          for (const runId of runIdsToDelete) {
            await github.rest.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            console.log(`Deleted workflow run with ID: ${runId}`);
          }
